### ISSUE TITLE
Is this codelab still accurate?  getting the following errors...

### ISSUE THREAD

**Issue by mingsf** [firebase/friendlyeats-web#33]
index.esm.js:356 Uncaught 
{code: "app/no-app", message: "Firebase: No Firebase App '[DEFAULT]' has been cre…- call Firebase App.initializeApp() (app/no-app).", name: "[DEFAULT]", stack: "[DEFAULT]: Firebase: No Firebase App '[DEFAULT]' h…s.firebaseapp.com/scripts/FriendlyEats.js:196:16)"}
code
:
"app/no-app"
message
:
"Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)."
name
:
"[DEFAULT]"
stack
:
"[DEFAULT]: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).↵    at cr (https://fs3friendlyeats.firebaseapp.com/__/firebase/5.1.0/firebase-app.js:1:32616)↵    at i (https://fs3friendlyeats.firebaseapp.com/__/firebase/5.1.0/firebase-app.js:1:34457)↵    at Object.f [as auth] (https://fs3friendlyeats.firebaseapp.com/__/firebase/5.1.0/firebase-app.js:1:33959)↵    at new FriendlyEats (https://fs3friendlyeats.firebaseapp.com/scripts/FriendlyEats.js:32:12)↵    at window.onload (https://fs3friendlyeats.firebaseapp.com/scripts/FriendlyEats.js:196:16)"
__proto__
:
Error

**Comment by nicolasgarnier** [comment]
@mingsf do you have a hosted version of your codelab somewhere we could have a look? You can deploy a version of your codelab by doing `firebase deploy` and please provide us the URL.

**Comment by nicolasgarnier** [comment]
Closing for inactivity
